src/Entity/Product.php
<?php

namespace App\Entity;

use DateTimeZone;
use App\Entity\ProductCategory;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProductRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 * @UniqueEntity("name", message="Ce nom est déjà utilisé !")
 */
class Product
{
    public const STATUS_AVAILABLE = 'En stock';
    public const STATUS_UNAVAILABLE = 'Indisponible';

    public function __toString()
    {
        return "product";
    }

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le nom du produit est obligatoire !")
     * @Assert\Length(min=3, max=255, minMessage="Le nom du produit doit avoir au moins {{ limit }} caractères", maxMessage="Le nom du produit doit avoir au plus {{ limit }} caractères")
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Le prix du produit est obligatoire !")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="La description du produit est obligatoire !")
     * @Assert\Length(min=10, minMessage="La description du produit doit avoir au moins {{ limit }} caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank(message="La date est obligatoire !")
     */
    private $date;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Le stock est obligatoire !")
     */
    private $stock;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $main_picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\ManyToOne(targetEntity=ProductCategory::class, inversedBy="products")
     * @Assert\NotBlank(message="La catégorie est obligatoire !")
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\OneToMany(targetEntity=PurchaseItem::class, mappedBy="product")
     */
    private $purchaseItems;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->purchaseItems = new ArrayCollection();
        $this->date = new \DateTime('now');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(?int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getMainPicture(): ?string
    {
        return $this->main_picture;
    }

    public function setMainPicture(?string $main_picture): self
    {
        $this->main_picture = $main_picture;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCategory(): ?ProductCategory
    {
        return $this->category;
    }

    public function setCategory(?ProductCategory $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getEntity(): ?string
    {
        return "product";
    }

    /**
     * @return Collection|PurchaseItem[]
     */
    public function getPurchaseItems(): Collection
    {
        return $this->purchaseItems;
    }

    public function addPurchaseItem(PurchaseItem $purchaseItem): self
    {
        if (!$this->purchaseItems->contains($purchaseItem)) {
            $this->purchaseItems[] = $purchaseItem;
            $purchaseItem->setProduct($this);
        }

        return $this;
    }

    public function removePurchaseItem(PurchaseItem $purchaseItem): self
    {
        if ($this->purchaseItems->removeElement($purchaseItem)) {
            // set the owning side to null (unless already changed)
            if ($purchaseItem->getProduct() === $this) {
                $purchaseItem->setProduct(null);
            }
        }

        return $this;
    }
}

src/Controller/CartController.php
<?php

namespace App\Controller;

use App\Repository\ProductRepository;
use App\Repository\ServiceRepository;
use App\Cart\CartService;
use App\Form\CartConfirmationType;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RequestStack;

class CartController extends AbstractController
{
    private $productRepository;
    private $serviceRepository;
    private $cartService;
    private $translator;
    private $requestStack;

    public function __construct(CartService $cartService, TranslatorInterface $translator,
    ProductRepository $productRepository, ServiceRepository $serviceRepository, RequestStack $requestStack)
    {
        $this->productRepository = $productRepository;
        $this->serviceRepository = $serviceRepository;
        $this->translator = $translator;
        $this->cartService = $cartService;
        $this->requestStack = $requestStack;
    }

    /**
     * @Route("/cart/add/{id}", name="cart_add", requirements={"id"="\d+"})
     */
    public function add($id)
    {
        $table = $this->requestStack->getCurrentRequest()->query->get('table');
        $this->cartService->add($id, $table);
        $repositoryTrans = $this->translator->trans($table);
        $this->addFlash('success', "Le $repositoryTrans a bien été ajouté au panier");
        $referer = $this->requestStack->getCurrentRequest()->headers->get('referer');
        return $this->redirect($referer);
    }

    /**
     * @Route("/cart", name="cart_show")
     */
    public function show()
    {
        $form = $this->createForm(CartConfirmationType::class);
        $detailedCart = $this->cartService->getDetailedCartItems();
        $total = $this->cartService->getTotal();
        return $this->render('cart/index.html.twig', [
            'items' => $detailedCart,
            'total' => $total,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/cart/delete/{id}", name="cart_delete", requirements={"id": "\d+"})
     */
    public function delete($id) {
        $table = $this->requestStack->getCurrentRequest()->query->get('table');
        $repository = $table . 'Repository';
        $item = $this->$repository->find($id);
        if (!$item) {
            throw $this->createNotFoundException("L'article n'existe pas et ne peut pas être supprimé");
        }
        $key = $table . '_' . $item->getId();
        $this->cartService->remove($key);
        $repositoryTrans = $this->translator->trans($table);
        $this->addFlash("success", "Le $repositoryTrans a bien été supprimé du panier");
        $referer = $this->requestStack->getCurrentRequest()->headers->get('referer');
        return $this->redirect($referer);
    }

    /**
     * @Route("/cart/decrement/{id}", name="cart_decrement", requirements={"id": "\d+"})
     */
    public function decrement($id){
        $table = $this->requestStack->getCurrentRequest()->query->get('table');
        $repository = $table . 'Repository';
        $item = $this->$repository->find($id);
        if (!$item) {
            throw $this->createNotFoundException("L'article n'existe pas et ne peut pas être décrémenté");
        }
        $key = $table . '_' . $item->getId();
        $this->cartService->decrement($key);
        $repositoryTrans = $this->translator->trans($table);
        $this->addFlash("success", "Le $repositoryTrans a bien été retiré");
        $referer = $this->requestStack->getCurrentRequest()->headers->get('referer');
        return $this->redirect($referer);
    }

}

templates/cart/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mon panier
{% endblock %}

{% block body %}
	<div class="row">
		<div class="col-7">
			<h3 class="my-5">Mon panier</h3>
			{% if items|length > 0 %}
				{% for key, item in items %}
					<div class="row">
						<div class="col-auto" style="width:200px">
							<img src="https://picsum.photos/400/400?image=562" alt="Image du produit" class="img-fluid d-block rounded">
						</div>
						<div class="col gx-5">
							<div class="d-flex justify-content-between fs-2">
								<p>{{item.item.name}}</p>
								<p>{{item.item.price * item.qty}}</p>
							</div>
							<p>
								{{ "Lorem ipsum dolor sit amet consectetur adipisicing elit. Vero repellendus ratione ipsam sapiente eaque expedita perspiciatis corrupti omnis magni optio nesciunt nam illo ducimus consectetur facere consequuntur dolore, in temporibus velit exercitationem. Pariatur quia incidunt, vitae, corporis provident modi hic maxime adipisci ex esse quis. Commodi, quaerat eos. Voluptatum, sint."|u.truncate(100, '...', false) }}
							</p>
							<div class="d-flex justify-content-between">
								<p>Taile : M</p>
								<p>{{item.qty}}
									<a href="{{path('cart_delete', {'id': item.item.id, 'table': item.item.entity})}}" class="btn btn-sm btn-danger">
										<i class="bi bi-trash me-1"></i>Supprimer</a>
									<a href="{{ path('cart_add', {'id': item.item.id, 'table': item.item.entity}) }}" class="btn btn-sm btn-link">
										<i class="bi bi-plus-square"></i>
									</a>
									<i class="fas fa-chevron-down"></i>
									<a href="{{ path('cart_decrement', {'id': item.item.id, 'table': item.item.entity}) }}" class="btn btn-sm btn-link">
										<i class="bi bi-dash-square"></i>
									</a>
								</p>
							</div>
						</div>
					</div>
					<hr>
				{% endfor %}
			{% else %}
				<h6>Le panier est vide</h6>
			{% endif %}
		</div>
		<div class="col-4 gx-5">
			<h3 class="mt-5 mb-2">Récapitulatif</h3>
			<div class="my-3">
				<div class="d-flex justify-content-between">
					<p>Sous-total</p>
					<p>{{total}}</p>
				</div>
				<div class="row justify-content-between">
					<p class="col-6">Frais estimés de prises en charges et d'expédition</p>
					<p class="col text-end">0 €</p>
				</div>
			</div>
			<hr>
			<div class="row justify-content-between">
				<h4 class="col-6">Total</h4>
				<h4 class="col text-end">{{total}}</h4>
			</div>
			<hr>
			<div class="d-flex justify-content-center">
				<a href="{{ path('purchase_confirm') }}" class="btn btn-light rounded-pill h3 px-5 mb-5">Paiement</a>
			</div>
			<div class="d-flex flex-column">
				<a href="#" class="h6">BESOIN D'AIDE ?</a>
				<a href="#">Livraison</a>
				<a href="#">Retour et remboursement</a>
				<a href="#">Commande et paiement</a>
				<a href="#">Promotions et codes de réduction</a>
			</div>
		</div>
	</div>
{% endblock %}