src/Entity/Product.php
<?php

namespace App\Entity;

use DateTimeZone;
use App\Entity\ProductCategory;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\ProductRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=ProductRepository::class)
 * @UniqueEntity("name", message="Ce nom est déjà utilisé !")
 */
class Product
{
    public const STATUS_AVAILABLE = 'En stock';
    public const STATUS_UNAVAILABLE = 'Indisponible';

    public function __toString()
    {
        return "product";
    }

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Le nom du produit est obligatoire !")
     * @Assert\Length(min=3, max=255, minMessage="Le nom du produit doit avoir au moins {{ limit }} caractères", maxMessage="Le nom du produit doit avoir au plus {{ limit }} caractères")
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Le prix du produit est obligatoire !")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank(message="La description du produit est obligatoire !")
     * @Assert\Length(min=10, minMessage="La description du produit doit avoir au moins {{ limit }} caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\NotBlank(message="La date est obligatoire !")
     */
    private $date;

    /**
     * @ORM\Column(type="integer")
     * @Assert\NotBlank(message="Le stock est obligatoire !")
     */
    private $stock;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $main_picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\ManyToOne(targetEntity=ProductCategory::class, inversedBy="products")
     * @Assert\NotBlank(message="La catégorie est obligatoire !")
     */
    private $category;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\OneToMany(targetEntity=PurchaseItem::class, mappedBy="product")
     */
    private $purchaseItems;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->purchaseItems = new ArrayCollection();
        $this->date = new \DateTime('now');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->stock;
    }

    public function setStock(?int $stock): self
    {
        $this->stock = $stock;

        return $this;
    }

    public function getMainPicture(): ?string
    {
        return $this->main_picture;
    }

    public function setMainPicture(?string $main_picture): self
    {
        $this->main_picture = $main_picture;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCategory(): ?ProductCategory
    {
        return $this->category;
    }

    public function setCategory(?ProductCategory $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getEntity(): ?string
    {
        return "product";
    }

    /**
     * @return Collection|PurchaseItem[]
     */
    public function getPurchaseItems(): Collection
    {
        return $this->purchaseItems;
    }

    public function addPurchaseItem(PurchaseItem $purchaseItem): self
    {
        if (!$this->purchaseItems->contains($purchaseItem)) {
            $this->purchaseItems[] = $purchaseItem;
            $purchaseItem->setProduct($this);
        }

        return $this;
    }

    public function removePurchaseItem(PurchaseItem $purchaseItem): self
    {
        if ($this->purchaseItems->removeElement($purchaseItem)) {
            // set the owning side to null (unless already changed)
            if ($purchaseItem->getProduct() === $this) {
                $purchaseItem->setProduct(null);
            }
        }

        return $this;
    }
}

src/Controller/Purchase/PurchaseConfirmationController.php
<?php

namespace App\Controller\Purchase;

use App\Entity\Purchase;
use App\Cart\CartService;
use App\Form\CartConfirmationType;
use App\Purchase\PurchasePersister;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PurchaseConfirmationController extends AbstractController
{
    private $cartService;
    private $em;
    private $persister;

    public function __construct(CartService $cartService, EntityManagerInterface $em, PurchasePersister $persister) {
        $this->cartService = $cartService;
        $this->em = $em;
        $this->persister = $persister;
    }
    /**
     * @Route("/purchase/confirm", name="purchase_confirm")
     * @IsGranted("ROLE_USER", message="Vous devez être connecté pour effectuer une commande")
     */
    public function confirm(Request $request) {
        $cartItems = $this->cartService->getDetailedCartItems();
        if (count($cartItems) === 0) {
            $this->addFlash("warning", 'Vous ne pouvez pas effectuer une commande avec un panier vide');
            return $this->redirectToRoute('cart_show');
        }
        $form = $this->createForm(CartConfirmationType::class);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();
            /** @var Purchase */
            $purchase = $form->getData();
            $this->persister->storePurchase($purchase);
            $this->em->flush();
            return $this->redirectToRoute('payment', [
                'id' => $purchase->getId()
            ]);
        }
        return $this->render('purchase/form.html.twig', [
            'form' => $form->createView()
        ]);
    }
}

src/Controller/Purchase/PurchasePaymentController.php
<?php

namespace App\Controller\Purchase;

use App\Entity\Purchase;
use App\Manager\PurchaseManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PurchasePaymentController extends AbstractController
{
    /**
     * @Route("/purchase/payment/{id}", name="payment", methods={"GET", "POST"})
     * @param Purchase $purchase
     * @return Response
     */
    public function payment(Purchase $purchase, PurchaseManager $purchaseManager): Response
    {
        if (!$purchase ||
        ($purchase && $purchase->getUser() !== $this->getUser()) ||
        ($purchase && $purchase->getStatus() === Purchase::STATUS_PAID)) {
            return $this->redirectToRoute('cart_show');
        }
        return $this->render('purchase/payment.html.twig', [
            'user' => $this->getUser(),
            'intentSecret' => $purchaseManager->intentSecret($purchase),
            'purchase' => $purchase
        ]);
    }

    /**
     * @Route("/user/subscription/{id}/paiement/load", name="subscription_paiement", methods={"GET", "POST"})
     * @param Purchase $purchase
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|Response
     * @throws \Exception
     */
    public function subscription(
        Purchase $purchase,
        Request $request,
        PurchaseManager $purchaseManager
    ){
        $user = $this->getUser();

        if($request->getMethod() === "POST") {
            $resource = $purchaseManager->stripe($_POST, $purchase);
            if(null !== $resource) {
                $purchaseManager->purchase_new($resource, $purchase, $user);
                return $this->redirectToRoute('purchase_payment_success', [
                    'id' => $purchase->getId(),
                    'intentSecret' => $purchaseManager->intentSecret($purchase)
                ]);
            }
        }
        return $this->redirectToRoute('payment', ['id' => $purchase->getId()]);
    }
}

src/Controller/Purchase/PurchasePaymentSuccessController.php
<?php

namespace App\Controller\Purchase;

use App\Entity\Purchase;
use App\Cart\CartService;
use App\Event\PurchaseSuccessEvent;
use App\Repository\PurchaseRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\EventDispatcher\EventDispatcherInterface;

class PurchasePaymentSuccessController extends AbstractController
{
    /**
     * @Route("/purchase/terminate/{id}", name="purchase_payment_success")
     * @IsGranted("ROLE_USER")
     */
    public function success($id, PurchaseRepository $purchaseRepository, EntityManagerInterface $em, CartService $cartService, EventDispatcherInterface $dispatcher) {
        $purchase = $purchaseRepository->find($id);
        if (!$purchase ||
            ($purchase && $purchase->getUser() !== $this->getUser()) ||
            ($purchase && $purchase->getStatus() === Purchase::STATUS_PAID)) {
            $this->addFlash('warning', 'La commande n\'existe pas');
            return $this->redirectToRoute("purchase_index");
        }
        $purchase->setStatus(Purchase::STATUS_PAID);
        $em->flush();
        $cartService->empty();

        $purchaseEvent = new PurchaseSuccessEvent($purchase);
        $dispatcher->dispatch($purchaseEvent, 'purchase.success');

        $this->addFlash("success", "La commande a bien été enregistré et le paiement a bien été validé");
        return $this->render("purchase/success.html.twig", [
            "purchase" => $purchase
        ]);
    }
}

src/Controller/Purchase/PurchasesListController.php
<?php

namespace App\Controller\Purchase;

use App\Entity\User;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class PurchasesListController extends AbstractController
{
    /**
     * @Route("/purchases", name="purchase_index")
     * @IsGranted("ROLE_USER", message="Vous devez être connecté pour accéder à vos commandes")
     */
    public function index() {
        /** @var User */
        $user = $this->getUser();
        return $this->render('purchase/index.html.twig', [
            'purchases' => $user->getPurchases()
        ]);
    }
}

templates/purchase/form.html.twig
{% extends "base.html.twig" %}
{% form_theme form _self %}
{% block body %}

	<div class="row justify-content-between">
		<h3 class="my-3 col-8 text-center">Paiement</h3>
		<div class="col-8 bg-light rounded-4 gx-5 py-3 mb-auto">
			<h4 class="mb-3">1. Options de livraison</h4>
			{{ form_start(form, {"attr": {"novalidate":"novalidate"}, 'action': path('purchase_confirm') }) }}
			<div class="row">
				<div class="col-sm">
					{{form_row(form.firstName)}}
				</div>
				<div class="col-sm-6">
					{{form_row(form.lastName)}}
				</div>
			</div>
			<div class="row">
				<div class="col">
					{{form_row(form.address, {"attr": {rows:1}})}}
				</div>
			</div>
			<div class="row">
				<div class="col-sm-2">
					{{form_row(form.postalCode)}}
				</div>
				<div class="col-sm">
					{{form_row(form.city)}}
				</div>
				<div class="col-sm-5">
					{{form_row(form.phone)}}
				</div>
			</div>
			<button type="submit" class="btn btn-success rounded-4 float-end">Valider</button>
			{{form_end(form) }}
		</div>
		<div class="col-3 bg-light rounded-4 gx-5">
			<div class="my-3">
				<div class="d-flex align-items-center justify-content-between">
					<h4>Votre panier</h4>
					<a href="#" class="">Modifier</a>
				</div>
				<div class="row justify-content-between">
					<p class="col-6">Sous-total</p>
					<p class="col text-end">0 €</p>
				</div>
				<div class="row justify-content-between">
					<p class="col-6">Frais d'expéditions estimés</p>
					<p class="col text-end">0 €</p>
				</div>
				<div class="d-flex justify-content-between align-items-baseline">
					<h4>Total</h4>
					<p class="">{{cartService.getTotal}}
						€</p>
				</div>
			</div>
			{% for item in cartService.getDetailedCartItems %}
				<div class="row mb-3">
					<div class="col-6">
						<img src="{{item.item.mainPicture}}" alt="image produit" class="img-fluid">
					</div>
					<div class="col">
						<h6>{{item.item.name}}</h6>
						<p class="mb-0">{{item.item.description|u.truncate(8, '...', false)}}</p>
						<p class="mb-0">taille : M</p>
						<p class="mb-0">Quantité :
							{{item.qty}}</p>
						<p class="mb-0">{{item.item.price * item.qty}}
							€</p>
					</div>
				</div>
			{% endfor %}
		</div>
	</div>
{% endblock %}

{% block form_row %}
	<div class="form-group mb-3">
		{{ form_label(form,'' , {'label_attr': {'class': 'mb-0 ps-2'} }) }}
		{{ form_widget(form, {'attr': {'class': 'form-control rounded-4'} }) }}
		{{ form_help(form) }}
		{{ form_errors(form) }}
	</div>
{% endblock %}

templates/purchase/index.html.twig
{% extends "base.html.twig" %}

{% block title %}
    Mes commandes
{% endblock %}

{% block body %}
    <h3>Mes commandes</h3>

    <table class="table">
        <thead>
            <tr>
                <th>Numéro</th>
                <th>Adresse</th>
                <th>Date de commande</th>
                <th>Articles</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            {% for purchase in purchases %}
                <tr>
                    <td>{{purchase.id}}</td>
                    <td>{{purchase.address}}<br>{{purchase.postalCode}}, {{purchase.city}}</td>
                    <td>{{purchase.purchasedAt|date('d/m/Y à H:i')}}</td>
                    <td>
                        <ul>
                            {% for item in purchase.purchaseItems %}
                                <li>{{item.quantity == 1 ? '' : item.quantity ~ 'x '}}{{item.itemName}} ({{item.total / 100}}) €</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>{{purchase.total / 100}} €</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/purchase/payment.html.twig
{% extends "base.html.twig" %}
{% block title %}
	Payez votre commande
{% endblock %}
{% block stylesheets %}
	{{ parent() }}
	{{ encore_entry_link_tags('paymentCss') }}
{% endblock %}

{% block body %}
	{% if app.user %}
		<h3>Payez votre commande</h3>
		<section class="features-icons bg-light text-center rounded-4">
			<div class="row">
				<div class="col">
					<div class="card-body">
						<form action="{{ path("subscription_paiement", {'id': purchase.id }) }}" method="post" id="payment-form">
							<div class="form-row">
								<div id="card-elements"></div>
								<script src="https://js.stripe.com/v3/"></script>
								<div id="card-errors" role="alert"></div>
							</div>
							<button class="btn btn-success mt-4">
								Acheter ({{ purchase.total }})
							</button>
						</form>
					</div>
				</div>
			</div>
		</section>
	{% else %}
		<h3>Vous devez être connecté pour confirmer cette commande</h3>
		<a href="{{path('app_login')}}" class="btn btn-success">Connexion</a>
		ou
		<a href="#">Créez un compte</a>
	{% endif %}
{% endblock %}

{% block javascripts %}
	{{ parent() }}
	{{ encore_entry_script_tags('payment') }}
	<script>
		{% if app_environement == 'dev' %}
const stripeToken = "{{ stripe_public_key_dev }}";
{% else %}
const stripeToken = "{{ stripe_public_key_prod }}";{% endif %}const stripe = Stripe(stripeToken);
const elements = stripe.elements();
const subscription = "{{ purchase.id }}";
const clientSecret = "{{ intentSecret }}";
const cardholderName = "{{ app.user.pseudo }}";
const cardholderEmail = "{{ app.user.email }}";
	</script>
{% endblock %}

templates/purchase/success.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<h3>Récapitulatif de votre commande</h3>
	{% for item in purchase.purchaseItems %}
		<div class="bg-light rounded-4 my-3 p-3">
			<h5>{{item.itemName}}</h5>
			<p>Prix :
				{{item.itemPrice}}
				€</p>
			<p>Quantité :
				{{item.quantity}}</p>
			<p class="mb-0">Total :
				{{item.total}}
				€</p>
		</div>
	{% endfor %}
{% endblock %}